# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Ignore WASM
          command: rm -rf wasm
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - run:
          name: Run benchmark
          command: cd test && go test -bench=. -benchmem
      - store_test_results:
          path: /tmp/test-reports
  build-wasm:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Build WASM
          command: cd wasm && GOOS=js GOARCH=wasm go build -o imgpro.wasm
      - run:
          name: WASM Exec Script
          command: cd wasm && cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .
      - persist_to_workspace:
          root: wasm
          paths:
            - imgpro.wasm
            - index.html
            - wasm_exec.js
  docs-deploy:
    # refs: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: wasm
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "82163514@qq.com"
            git config user.name "echosoar"
      - add_ssh_keys:
          fingerprints:
            - "99:5d:22:cc:75:23:3b:0a:1e:f3:a1:b6:ed:8e:a9:25"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist wasm


workflows:
  version: 2
  build:
    jobs:
      - test
      - build-wasm
      - docs-deploy:
          requires:
            - test
            - build-wasm
          filters:
            branches:
              only: main